### PR TITLE
Prepare n-t-inmemory-0.5 release.

### PR DESCRIPTION
**Pull request by qnikst**
Facundo, please, can you recheck everything we need to release this version and do a release. Thanks.

### CODE REVIEW

**Comment by facundominguez** [comment]
Fix the CONTRIBUTING.md file?

**Comment by facundominguez** [comment]
CI is not running any tests, is it?

**Comment by facundominguez** [comment]
We will need to explain in the readme what this package is good for and what the limitations are. The reference to the cloud-haskell web site is not very helpful.

**Comment by qnikst** [comment]
1. CONTRIBUTING.md is fixed in master, should I rebase?

2.

```
+script:
+  - cabal install --enable-tests --run-tests
```

This function runs all tests AFAIU

**Comment by facundominguez** [comment]
> This function runs all tests AFAIU

Can you copy the output of travis when running tests? It looks to me like it is skipping them.

**Comment by qnikst** [comment]
Done

**Comment by facundominguez** [comment]
Merged as 46d6740.

**Pull request closed without merging**
