### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by facundominguez** [comment]
LGTM

**Comment by qnikst** [comment]
@facundominguez, @mboes PTAL.
I have removed debatable parts, and the only change in this patch is to not convert `Closed` connections to `Failed`.

**Comment by mboes** [comment]
:+1:

**Comment by facundominguez** [comment]
:+1:

**Comment by mboes** [comment]
Ah one thing I forget to mention earlier: IIUC this bug was caught by d-p-tests, but not n-t-tests, right? If so, we need an extra regression test in n-t-tests.

**Comment by qnikst** [comment]
D-p test do not depend on this fix. The part that I have excluded was implemented because of d-p test, but it's here now.

**Comment by qnikst** [comment]
Travis error is not related to the real problems so merging:

```
Downloading the latest package list from hackage.haskell.org

cabal:

/home/travis/.cabal/packages/hackage.haskell.org/00-index.tar.gz2151.tmp:

resource exhausted
```

**Pull request merged**
